modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0-only"
[[mods]]
modId="oculus"
version="${version}"
displayName="Mekalus (Oculus)"
logoFile="oculus-logo.png"
authors="KostromDan, coderbot, IMS212, Justsnoopy30, FoundationGames"
description='''
Unofficial Fork of "Oculus", made to fix MekaSuit rendering with shaders.
'''

[[dependencies.oculus]]
modId="forge"
mandatory=true
versionRange="[43.1.58,)"
side="BOTH"

[mods."sodium:options"]
"mixin.features.sky"=false